site_name: Maiusebi's Godot DevKit
repo_url: https://github.com/jmebia/gd-shader-lib

nav:
  - Home: index.md
  - Shaders:
    - shaders/index.md
    - Brightness: shaders/brightness.md
    - Dissolve: shaders/dissolve.md
    - Flash: shaders/flash.md
    - Saturation: shaders/saturation.md
    - Silhoutte: shaders/silhoutte.md

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  palette: 
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto Mono
    code: Fira Code
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tabs
    - toc.follow
    - content.code.annotate
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmebia
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jmebia/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Maiusebi
    - icon: fontawesome/solid/paper-plane
      link: mailto:jm.ebia@kodeteq.com
  generator: false
  favicon: assets/favicon.ico

copyright: Copyright &copy; 2025 Josiah Maius S. Ebia